import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {useEffect, useState} from "react";
import axios from "axios";
import Image from 'next/image'

const inter = Inter({ subsets: ["latin"] });

export default function Characters() {
    const [characters, setCharacters] = useState< null | CharacterType[]>(null)
    useEffect(()=>{
        axios.get('https://rickandmortyapi.com/api/character')
            .then(res=>{
                setCharacters(res.data.results)
            })
    },[])

  return (
    <>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          {
              characters && characters.map((character:CharacterType)=>(
                  <div key={character.id}>
                      <div>{character.name}</div>
                      <Image alt={`Picture of ${character.name}`} src={character.image} width={300} height={300}/>
                  </div>
              ))
          }
      </main>
    </>
  );
}
type CharacterType ={
    id: number
    name: string
    image: string
}